# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

before_script:
    - apt-get -y update -yqq
    - apt-get install -y lsb-release
    - apt install -y software-properties-common
    - bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - export CARGO_HOME=.cargo-cache
    - rustc --version
    - cargo --version

# Use cargo to test the project
test:cargo:
    script:
      - rustc --version && cargo --version  # Print version info for debugging
      - cargo test --workspace --verbose
  