[package]
name = "rain-codegen-llvm"
version = "0.0.0"
authors = ["Jad Ghalayini <jad.ghalayini@hotmail.com>"]
edition = "2018"

[dependencies]
rain-lang = { git = "https://gitlab.com/tekne/rain.git" }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm10-0" }
fxhash = "0.2.1"